language: node_js
node_js:
- '8'
env:
  global:
  - secure: DGiwkAKVUXu3kzl2Ks1dr+sXhai/Ub+oHosbd6Zf5YqNfH7WjrbosbflGGt6Z6P0Sz6UUclF7LA6xHtrASBu9Wi7DZN8pVkc0Dxj4zf7G9dL5UYMtfd7VOL8HGMHONxKMGugnKpTTPtEg2y202jn+S+ytV822EvP0duo1X6xekqsE1o4uOmmV9Squ38naB4QZNRW1XAUyk31+bTAWUNuVS9EbT8A4UpwXIAgNdfnCuaEqtO/+gUhvVRIX4FTJ4O3zAOW5xXuGAbCX/f6D1jQAwaUuzDM3s4uVPYbkl4guKD5LioyWUAFlZ+8pX0pIbIalSY8XbQ5vDCvF4w9EBG+jSQ8BlZj0QsK6HBv0DPrhPBdns9rtaan/KLMxMVqcRtkxo850kZDLf2vdub/ieIkTnygU2iQmZcgDo1jf3UipV914giXsHiW49mbsn8f9ppWE+jArSmzsgsTzxRkg+ITMV/1TMzAJ+LhMcGU58jIp1j/bsohNdOnmyI4lGSKODauCeFRRuGfjsHIRJWGUBWDEuYGo8iSY/8L2WeBp08yspuf+6LvynGZS2c0e9sTt2zcFs7SILLGp4ZlFwsk/Ji1RWSGULKFQHgxpt3c4gakfR2BWFaeDRSqq2lwBCC+yWEezapPD3DeoxlcDNGo8VEYGXYbUZme5rJmGVIcciwjnYg=
dist: trusty
sudo: false
addons:
  chrome: stable
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm run broker
after_success:
- bash travis/commit.sh
deploy:
  api_key:
    secure: aNXDVQbee5z3R0MFOxnq36DTVhqt8ztkorNKLCXyhhWdBCNIPITbmgqr2/4euvMMRlwxq5t9LfRqhGOueaV0fZ8erYjgBOFoSQfZ2S8KAzomvqed0ikhyozoDw5jTizYfkmP5aARgkE/OuMtP6Zp+1mmKyxmrrFHHX6AVM3I5m052UbnM/VyMsJl+2D1yRqatjcTE1s7h4EJ2cBNhD6L0VidT5xUtRSNjEXFbC474tCsFRvKuRH49R+JDyPa6sf173uSw5FxSIO3pIxKyTfmhWmwKgAChyzB0Gu+QH+eF4ZYMUsIKDl/yFi6A+1aMPz3pxx7OdFwXwExj3CZ29/FeUZqduTlXDgKty7eALEZeM7y5wBxTPSpv3CmQzZssV3dUhSmn27PiW3gD1XtrMVBqQ+e9zjClgsvP6MOWPt0Zp5wbG6AwuLPUi1lTbVQKLPA3iCJtSsVYLtWCHBkKpPD7/EPFPFeOpVpaeIgwfTh0+aWvGDj+erpf6Nyk164lkpZLhDRFGgVLuch27ZqZVlXaWDMUHiHkLjuLBumuv9s0B4wYTSrbhNWwsRcr7UM9LuNtmvdoOqgV5QWNBdxeF7wXdKDAbFLDoJgjMT71upyxMGsRL+Op827brElAIKGO3ql0AfplCToITyqcf7iZ+OBqE0+ExYswBXuqYmaKkZgw30=
